apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dxi.yaml
  - dd.yaml
  - i6000.yaml
  - networker.yaml
  - networker-core.yaml
  - networker-chnl.yaml
  - networker-info.yaml
  - networker-ifrs.yaml
  - zfs.yaml
