apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-dashboard-networker-hostname-classification
  labels:
    app: backup-dashboard-collector
    collector-group: networker
data:
  hostname_domain.csv: |
    hostname,security_domain
