app:
  name: backup-dashboard-collector-dxi
  log_level: INFO

elasticsearch:
  enabled: false
  hosts:
    - https://elasticsearch:9200
  index_prefix: backup-dashboard
  username: elasticsearch_username_TO_BE_FILLED
  password: elasticsearch_password_TO_BE_FILLED
  verify_certs: true
  ca_certs: /apps/secrets/elasticsearch/ca.crt

collectors:
  - name: DXi_1
    type: DXi
    protocol: cli
    enabled: true
    schedule:
      interval_minutes: 5
      minute_offset: 0
      second: 0
    host: DXi_1_host_TO_BE_FILLED
    ssh_port: 22
    ssh_key_path: /apps/secrets/ssh/id_rsa
    ssh_known_hosts_path: /apps/secrets/ssh/known_hosts
    jump_host: relay_host_TO_BE_FILLED
    jump_port: 22
    jump_username: "123456789"
    jump_ssh_key_path: /apps/secrets/ssh/id_rsa
    username: root
    command_timeout: 30
    commands:
      common_components: "syscli --getstatus commoncomponent"
      storage_arrays: "syscli --getstatus storagearray"
      system_board: "syscli --getstatus systemboard"
      capacity: "syscli --get diskusage"
      dedup: "syscli --get datareductionstat"
      vtls: "syscli --list vtl"
      interfaces: "syscli --getstatus networkport"
      network_config: "syscli --show netcfg"
      admin_alerts: "syscli --list adminalert"
      service_tickets: "syscli --list serviceticket --open"

  - name: DXi_2
    type: DXi
    protocol: cli
    enabled: true
    schedule:
      interval_minutes: 5
      minute_offset: 0
      second: 0
    host: DXi_2_host_TO_BE_FILLED
    ssh_port: 22
    ssh_key_path: /apps/secrets/ssh/id_rsa
    ssh_known_hosts_path: /apps/secrets/ssh/known_hosts
    jump_host: relay_host_TO_BE_FILLED
    jump_port: 22
    jump_username: "123456789"
    jump_ssh_key_path: /apps/secrets/ssh/id_rsa
    username: root
    command_timeout: 30
    commands:
      common_components: "syscli --getstatus commoncomponent"
      storage_arrays: "syscli --getstatus storagearray"
      system_board: "syscli --getstatus systemboard"
      capacity: "syscli --get diskusage"
      dedup: "syscli --get datareductionstat"
      vtls: "syscli --list vtl"
      interfaces: "syscli --getstatus networkport"
      network_config: "syscli --show netcfg"
      admin_alerts: "syscli --list adminalert"
      service_tickets: "syscli --list serviceticket --open"
